modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Skilles/SpokenWord/issues"
license = "MIT"

[[mods]]
modId = "spokenword"
version = "${version}"
displayName = "Spoken Word"
authors = "Skilles"
description = '''
Send chat messages or commands on certain game events
'''
#logoFile = ""

[[dependencies.spokenword]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spokenword]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spokenword]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.spokenword]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "[3.2.1+1.20,)"
ordering = "NONE"
side = "CLIENT"